#!/usr/bin/env bash

if [[ -s "/home/ralbaredo/.rvm/environments/ruby-1.9.2-head" ]]
then
  source "/home/ralbaredo/.rvm/environments/ruby-1.9.2-head"
  exec ruby "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ralbaredo/.rvm/environments/ruby-1.9.2-head'" >&2
  exit 1
fi
  