# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1317967675);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1317967867);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1317967868);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1317967079);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1317967567);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.23");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.enabledItems", "langpack-en-GB@firefox-3.6.ubuntu.com:3.6,ubufox@ubuntu.com:0.9rc2,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.23");
user_pref("extensions.lastAppVersion", "3.6.23");
user_pref("extensions.update.notifyUser", false);
user_pref("idle.lastDailyNotification", 1317979406);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.last_vacuum", 1317979406);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.warn_viewing_mixed", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1320558978);
